[package]
name = "easypub"
version = "0.1.0"
authors = ["hoolooday@live.com"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.0"
rfd = "0.11.4"
[build-dependencies]
slint-build = "1.0"
